#!/usr/bin/env python3
"""
Scale Sensitivity Analysis for MAFIS.

RQ3: How does fleet size affect fault tolerance?

Reads results/scale_sensitivity_runs.csv, computes:
  1. FT ratios per fleet size × scenario
  2. Mann-Whitney U significance tests (BH-FDR corrected)
  3. LaTeX table (fleet size × scenario FT matrix)
  4. SVG curve plot (FT ratio vs fleet size per scenario)

Usage:
  python3 analysis/scale_sensitivity_analysis.py

Outputs (in results/):
  scale_sensitivity_metrics.csv  -- FT, CI, p-values per (num_agents, scenario)
  scale_sensitivity_table.tex    -- LaTeX table for paper
  scale_sensitivity_curves.svg   -- FT ratio curves per scenario
"""

import csv
import math
import os
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(__file__))
from stats import (
    load_runs, pair_runs, mean, ci95, mann_whitney_u,
    cliffs_delta, benjamini_hochberg, format_p, RESULTS_DIR,
)
from constants import SCENARIO_ORDER, SCENARIO_LABEL, SCENARIO_LABEL_SHORT


SCENARIO_COLORS = {
    "burst_20pct":         "#e07b39",
    "burst_50pct":         "#e74c3c",
    "wear_medium":         "#f39c12",
    "wear_high":           "#8e44ad",
    "zone_50t":            "#4a9eca",
    "intermittent_80m15r": "#1abc9c",
    "perm_zone_100pct":    "#c0392b",
}


# ---------------------------------------------------------------------------
# FT ratio computation
# ---------------------------------------------------------------------------

def compute_ft_ratios(pairs):
    """Group by (num_agents, scenario); compute FT = fault_throughput / baseline."""
    ratios = defaultdict(list)
    baselines = defaultdict(list)
    faults = defaultdict(list)
    for (solver, topology, scenario, scheduler, num_agents, seed), data in pairs.items():
        bl = data.get("baseline", float("nan"))
        ft = data.get("fault", float("nan"))
        if math.isnan(bl) or math.isnan(ft) or bl == 0:
            continue
        key = (num_agents, scenario)
        ratios[key].append(ft / bl)
        baselines[key].append(bl)
        faults[key].append(ft)
    return ratios, baselines, faults


# ---------------------------------------------------------------------------
# Output: metrics CSV
# ---------------------------------------------------------------------------

def write_metrics_csv(ratios, baselines, faults, adjusted_p):
    path = os.path.join(RESULTS_DIR, "scale_sensitivity_metrics.csv")
    densities = sorted(set(k[0] for k in ratios))
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow([
            "num_agents", "scenario", "n_seeds",
            "ft_mean", "ft_ci95_lo", "ft_ci95_hi",
            "baseline_mean", "fault_mean",
            "mw_p_raw", "mw_p_adj", "cliffs_d",
        ])
        for n in densities:
            for scenario in SCENARIO_ORDER:
                key = (n, scenario)
                rs = ratios.get(key, [])
                if not rs:
                    continue
                bl = baselines.get(key, [])
                ft = faults.get(key, [])
                r_mean = mean(rs)
                r_lo, r_hi = ci95(rs)
                u, p = mann_whitney_u(ft, bl)
                cd = cliffs_delta(ft, bl)
                p_adj = adjusted_p.get(key, float("nan"))
                w.writerow([
                    n, scenario, len(rs),
                    f"{r_mean:.4f}", f"{r_lo:.4f}", f"{r_hi:.4f}",
                    f"{mean(bl):.4f}", f"{mean(ft):.4f}",
                    f"{p:.4f}" if not math.isnan(p) else "",
                    f"{p_adj:.4f}" if not math.isnan(p_adj) else "",
                    f"{cd:.3f}" if not math.isnan(cd) else "",
                ])
    print(f"Saved: {path}")


# ---------------------------------------------------------------------------
# Output: LaTeX table
# ---------------------------------------------------------------------------

def write_latex_table(ratios, adjusted_p):
    path = os.path.join(RESULTS_DIR, "scale_sensitivity_table.tex")
    densities = sorted(set(k[0] for k in ratios))
    col_spec = "r" + "c" * len(SCENARIO_ORDER)

    lines = [
        "% Scale sensitivity table — auto-generated by analysis/scale_sensitivity_analysis.py",
        "% Cells: mean FT ratio. * BH-adj. p < 0.05.",
        "",
        "\\begin{table}[ht]",
        "  \\caption{FT ratio by fleet size (RQ3: scale sensitivity). "
        "Controlled: PIBT solver, warehouse topology, random scheduler. "
        "$^*$ BH-adj.~$p < 0.05$.}",
        "  \\label{tab:scale_sensitivity}",
        "  \\centering",
        "  \\footnotesize",
        f"  \\begin{{tabular}}{{{col_spec}}}",
        "    \\toprule",
    ]
    sc_hdrs = " & ".join(f"\\textbf{{{SCENARIO_LABEL.get(s, s)}}}" for s in SCENARIO_ORDER)
    lines.append(f"    $n$ & {sc_hdrs} \\\\")
    lines.append("    \\midrule")

    for n in densities:
        cells = [str(n)]
        for scenario in SCENARIO_ORDER:
            key = (n, scenario)
            rs = ratios.get(key, [])
            if not rs:
                cells.append("—")
                continue
            r = mean(rs)
            p_adj = adjusted_p.get(key, 1.0)
            sig = not math.isnan(p_adj) and p_adj < 0.05
            cells.append(f"${r:.3f}{'{}^*' if sig else ''}$")
        lines.append("    " + " & ".join(cells) + " \\\\")

    lines += [
        "    \\bottomrule",
        f"    \\multicolumn{{{len(SCENARIO_ORDER)+1}}}{{l}}{{",
        "      \\footnotesize $^*$ BH-adj.~$p < 0.05$.}}",
        "  \\end{tabular}",
        "\\end{table}",
    ]

    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"Saved: {path}")


# ---------------------------------------------------------------------------
# Output: SVG line curves
# ---------------------------------------------------------------------------

def write_curves_svg(ratios):
    """FT ratio vs fleet size, one curve per scenario."""
    densities = sorted(set(k[0] for k in ratios))
    scenarios_with_data = [s for s in SCENARIO_ORDER if any((n, s) in ratios for n in densities)]

    W, H = 700, 360
    margin = {"top": 40, "right": 140, "bottom": 55, "left": 60}
    pw = W - margin["left"] - margin["right"]
    ph = H - margin["top"]  - margin["bottom"]
    x0, y0 = margin["left"], margin["top"]

    all_means = [mean(rs) for rs in ratios.values() if rs]
    y_min = max(0.0, min(all_means) - 0.05) if all_means else 0.0
    y_max = max(all_means) + 0.10 if all_means else 1.5
    y_min = min(y_min, 0.85)
    y_max = max(y_max, 1.10)
    y_range = y_max - y_min

    d_idx = {d: i for i, d in enumerate(densities)}
    x_scale = pw / (len(densities) - 1) if len(densities) > 1 else pw
    y_scale = ph / y_range if y_range else ph

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}">',
        f'  <rect width="{W}" height="{H}" fill="#1a1a2e"/>',
        f'  <style>text {{ font-family: monospace; fill: #c8c8d4; }}</style>',
        f'  <rect x="{x0}" y="{y0}" width="{pw}" height="{ph}" fill="#12122a" rx="2"/>',
        f'  <text x="{x0+pw//2}" y="22" text-anchor="middle" font-size="11" fill="#a0a0c0">'
        f'FT Ratio vs Fleet Size (PIBT, warehouse topology)</text>',
    ]

    # Grid lines + y labels
    for tick in [y for y in [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4]
                 if y_min <= y <= y_max]:
        ty = y0 + ph - (tick - y_min) * y_scale
        baseline_style = 'stroke="#556" stroke-width="1.5" stroke-dasharray="6,3"'
        grid_style     = 'stroke="#333" stroke-width="1"   stroke-dasharray="3,3"'
        style = baseline_style if abs(tick - 1.0) < 0.001 else grid_style
        lines.append(f'  <line x1="{x0}" y1="{ty:.1f}" x2="{x0+pw}" y2="{ty:.1f}" {style}/>')
        lines.append(f'  <text x="{x0-5}" y="{ty+4:.1f}" text-anchor="end" font-size="10">{tick:.2f}</text>')

    # x labels
    for d in densities:
        tx = x0 + d_idx[d] * x_scale
        lines.append(f'  <text x="{tx:.1f}" y="{y0+ph+16}" text-anchor="middle" font-size="10">{d}</text>')

    # Axis lines
    lines.append(f'  <line x1="{x0}" y1="{y0}" x2="{x0}" y2="{y0+ph}" stroke="#444" stroke-width="1"/>')
    lines.append(f'  <line x1="{x0}" y1="{y0+ph}" x2="{x0+pw}" y2="{y0+ph}" stroke="#444" stroke-width="1"/>')

    # Curves
    for scenario in scenarios_with_data:
        color  = SCENARIO_COLORS.get(scenario, "#888")
        points = []
        for d in densities:
            rs = ratios.get((d, scenario), [])
            if rs:
                x = x0 + d_idx[d] * x_scale
                y = y0 + ph - (mean(rs) - y_min) * y_scale
                points.append((x, y))
        if len(points) >= 2:
            d_attr = "M" + " L".join(f"{x:.1f},{y:.1f}" for x, y in points)
            lines.append(f'  <path d="{d_attr}" stroke="{color}" stroke-width="2" fill="none" opacity="0.9"/>')
        for x, y in points:
            lines.append(f'  <circle cx="{x:.1f}" cy="{y:.1f}" r="4" fill="{color}"/>')

    # Legend (right panel)
    lx, ly = W - margin["right"] + 10, y0
    for scenario in scenarios_with_data:
        color = SCENARIO_COLORS.get(scenario, "#888")
        label = SCENARIO_LABEL_SHORT.get(scenario, scenario)
        lines.append(f'  <line x1="{lx}" y1="{ly+6}" x2="{lx+16}" y2="{ly+6}" stroke="{color}" stroke-width="2"/>')
        lines.append(f'  <text x="{lx+20}" y="{ly+10}" font-size="9">{label}</text>')
        ly += 22

    # Axis titles
    lines.append(
        f'  <text transform="rotate(-90)" x="{-(y0+ph//2)}" y="14" '
        f'text-anchor="middle" font-size="10">FT Ratio (fault / baseline)</text>'
    )
    lines.append(f'  <text x="{x0+pw//2}" y="{H-5}" text-anchor="middle" font-size="10">Fleet Size (agents)</text>')

    lines.append("</svg>")

    path = os.path.join(RESULTS_DIR, "scale_sensitivity_curves.svg")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"Saved: {path}")


# ---------------------------------------------------------------------------
# Console summary
# ---------------------------------------------------------------------------

def print_summary(ratios, baselines, faults, adjusted_p):
    densities = sorted(set(k[0] for k in ratios))

    print("\n" + "=" * 78)
    print("SCALE SENSITIVITY — RQ3: Does fleet size affect fault tolerance?")
    print("=" * 78)
    print(f"{'Agents':>6} {'Scenario':<22} {'FT':>7} {'95% CI':>17} {'p_adj':>8} {'Cliff':>6}")
    print("-" * 78)

    for scenario in SCENARIO_ORDER:
        prev_ft = None
        for n in densities:
            key = (n, scenario)
            rs  = ratios.get(key, [])
            if not rs:
                continue
            ft   = faults.get(key, [])
            bl   = baselines.get(key, [])
            r    = mean(rs)
            lo, hi = ci95(rs)
            p_adj  = adjusted_p.get(key, float("nan"))
            cd     = cliffs_delta(ft, bl)
            sig    = not math.isnan(p_adj) and p_adj < 0.05
            cd_str = f"{cd:>6.3f}" if not math.isnan(cd) else "   —  "
            trend  = ""
            if prev_ft is not None:
                trend = " ↓" if r < prev_ft - 0.02 else (" ↑" if r > prev_ft + 0.02 else "  ")
            print(f"{n:>6} {scenario:<22} {r:>7.3f} [{lo:.3f},{hi:.3f}] "
                  f"{format_p(p_adj):>9}  {cd_str}{trend}")
            prev_ft = r
        print()

    # Directional summary
    print("--- Δ FT from smallest (n=10) to largest (n=80) fleet ---")
    for scenario in SCENARIO_ORDER:
        lo_rs = ratios.get((densities[0],  scenario), [])
        hi_rs = ratios.get((densities[-1], scenario), [])
        if lo_rs and hi_rs:
            delta = mean(hi_rs) - mean(lo_rs)
            arrow = "↓" if delta < -0.05 else ("↑" if delta > 0.05 else "≈")
            print(f"  {scenario:<22}: {mean(lo_rs):.3f} → {mean(hi_rs):.3f}  "
                  f"Δ={delta:+.3f} {arrow}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("Loading scale_sensitivity_runs.csv...")
    rows = load_runs("scale_sensitivity_runs.csv")
    print(f"  {len(rows)} rows loaded")

    pairs = pair_runs(rows)
    print(f"  {len(pairs)} paired configs")

    ratios, baselines, faults = compute_ft_ratios(pairs)
    densities = sorted(set(k[0] for k in ratios))
    print(f"  {len(ratios)} groups — fleet sizes: {densities}")

    print("\nComputing BH-FDR adjusted p-values...")
    raw_p = []
    for n in densities:
        for scenario in SCENARIO_ORDER:
            key = (n, scenario)
            bl  = baselines.get(key, [])
            ft  = faults.get(key, [])
            if bl and ft:
                _, p = mann_whitney_u(ft, bl)
                raw_p.append((key, p))
            else:
                raw_p.append((key, float("nan")))

    adjusted_p = benjamini_hochberg(raw_p)
    n_adj = sum(1 for p in adjusted_p.values() if not math.isnan(p) and p < 0.05)
    print(f"  BH-adjusted significant: {n_adj} / {len(raw_p)}")

    print("\nWriting outputs...")
    write_metrics_csv(ratios, baselines, faults, adjusted_p)
    write_latex_table(ratios, adjusted_p)
    write_curves_svg(ratios)

    print_summary(ratios, baselines, faults, adjusted_p)


if __name__ == "__main__":
    main()
