/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const experiment_finish: () => [number, number];
export const experiment_run_single: (a: number, b: number) => [number, number];
export const experiment_start: () => void;
export const get_simulation_state: () => [number, number];
export const send_command: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h1f80bddcd6d5d5d3: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h310e94b1ca27a306: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h2899a6c619b176ed: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2e29d3079f3950e2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2e29d3079f3950e2_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2e29d3079f3950e2_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2e29d3079f3950e2_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2e29d3079f3950e2_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2e29d3079f3950e2_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2e29d3079f3950e2_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2e29d3079f3950e2_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h8856b7c40a3a02e1: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h18d2b746b5616879: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
